// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzNU2nMcYv4MVPWdYg9UOhfz0_vQwMVY',
    appId: '1:634422634299:web:149c00962402a46c65f91e',
    messagingSenderId: '634422634299',
    projectId: 'fir-curd-60b78',
    authDomain: 'fir-curd-60b78.firebaseapp.com',
    databaseURL: 'https://fir-curd-60b78-default-rtdb.firebaseio.com',
    storageBucket: 'fir-curd-60b78.appspot.com',
    measurementId: 'G-FHVLJ2HB0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoxS79cNTox3Jd6JvSR2RuOSSoiLXVzk',
    appId: '1:634422634299:android:30e2b05615cfdcb865f91e',
    messagingSenderId: '634422634299',
    projectId: 'fir-curd-60b78',
    databaseURL: 'https://fir-curd-60b78-default-rtdb.firebaseio.com',
    storageBucket: 'fir-curd-60b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxOqKEZDOx9Gk_BEljdBVembSLBp695M',
    appId: '1:634422634299:ios:a7f58315b1f296c365f91e',
    messagingSenderId: '634422634299',
    projectId: 'fir-curd-60b78',
    databaseURL: 'https://fir-curd-60b78-default-rtdb.firebaseio.com',
    storageBucket: 'fir-curd-60b78.appspot.com',
    iosClientId: '634422634299-vl6nm1eosfp2n90bcp01vj43735k5vl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxOqKEZDOx9Gk_BEljdBVembSLBp695M',
    appId: '1:634422634299:ios:a7f58315b1f296c365f91e',
    messagingSenderId: '634422634299',
    projectId: 'fir-curd-60b78',
    databaseURL: 'https://fir-curd-60b78-default-rtdb.firebaseio.com',
    storageBucket: 'fir-curd-60b78.appspot.com',
    iosClientId: '634422634299-vl6nm1eosfp2n90bcp01vj43735k5vl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAysdnXO0Tbmk7osQPtbzcM1zzNr3ujGZk',
    appId: '1:634422634299:web:f0f2e02a98c267c865f91e',
    messagingSenderId: '634422634299',
    projectId: 'fir-curd-60b78',
    authDomain: 'fir-curd-60b78.firebaseapp.com',
    databaseURL: 'https://fir-curd-60b78-default-rtdb.firebaseio.com',
    storageBucket: 'fir-curd-60b78.appspot.com',
    measurementId: 'G-KS9FY00L2W',
  );

}